/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmployeeImport } from './routes/employee'

// Create Virtual Routes

const UserLazyImport = createFileRoute('/user')()
const PresensiLazyImport = createFileRoute('/presensi')()
const LoginLazyImport = createFileRoute('/login')()
const LeavesLazyImport = createFileRoute('/leaves')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UserLazyRoute = UserLazyImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/user.lazy').then((d) => d.Route))

const PresensiLazyRoute = PresensiLazyImport.update({
  id: '/presensi',
  path: '/presensi',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/presensi.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const LeavesLazyRoute = LeavesLazyImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/leaves.lazy').then((d) => d.Route))

const EmployeeRoute = EmployeeImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeImport
      parentRoute: typeof rootRoute
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/presensi': {
      id: '/presensi'
      path: '/presensi'
      fullPath: '/presensi'
      preLoaderRoute: typeof PresensiLazyImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/employee': typeof EmployeeRoute
  '/leaves': typeof LeavesLazyRoute
  '/login': typeof LoginLazyRoute
  '/presensi': typeof PresensiLazyRoute
  '/user': typeof UserLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/employee': typeof EmployeeRoute
  '/leaves': typeof LeavesLazyRoute
  '/login': typeof LoginLazyRoute
  '/presensi': typeof PresensiLazyRoute
  '/user': typeof UserLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/employee': typeof EmployeeRoute
  '/leaves': typeof LeavesLazyRoute
  '/login': typeof LoginLazyRoute
  '/presensi': typeof PresensiLazyRoute
  '/user': typeof UserLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employee' | '/leaves' | '/login' | '/presensi' | '/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employee' | '/leaves' | '/login' | '/presensi' | '/user'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/leaves'
    | '/login'
    | '/presensi'
    | '/user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  EmployeeRoute: typeof EmployeeRoute
  LeavesLazyRoute: typeof LeavesLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  PresensiLazyRoute: typeof PresensiLazyRoute
  UserLazyRoute: typeof UserLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  EmployeeRoute: EmployeeRoute,
  LeavesLazyRoute: LeavesLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  PresensiLazyRoute: PresensiLazyRoute,
  UserLazyRoute: UserLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/employee",
        "/leaves",
        "/login",
        "/presensi",
        "/user"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/employee": {
      "filePath": "employee.jsx"
    },
    "/leaves": {
      "filePath": "leaves.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/presensi": {
      "filePath": "presensi.lazy.jsx"
    },
    "/user": {
      "filePath": "user.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
